name: package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: generate tarball
        run: |
          cmake -B build -DENABLE_SDL=OFF -DENABLE_JOYSTICK=OFF
          cd build
          make package_source
      - name: release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "build/quasi88-*-Source.tar.xz"
          token: ${{ secrets.GITHUB_TOKEN }}
